name: 'Fetch Terraform Modules'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to fetch from terraform-cloud-modules-iac'
        required: true
        default: 'main'
        type: string
      destination_path:
        description: 'Destination path for modules'
        required: true
        default: './modules'
        type: string
      module_type:
        description: 'Type of modules to fetch (azure, aws, gcp)'
        required: true
        default: 'azure'
        type: choice
        options:
          - azure
          - aws
          - gcp
          - all

permissions:
  contents: read
  metadata: read

jobs:
  fetch-modules:
    name: 'Fetch Terraform Modules'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout core-infrastructure
      uses: actions/checkout@v3
    - name: Checkout terraform-cloud-modules-iac
      uses: actions/checkout@v3
      with:
        repository: joselrnz/terraform-cloud-modules-iac
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.API_TOKEN_TF }}
        path: terraform-cloud-modules-iac
        
    - name: Create destination directory
      run: mkdir -p ${{ github.event.inputs.destination_path }}
        
    - name: List repository contents
      run: |
        echo "Contents of terraform-cloud-modules-iac repository:"
        ls -la terraform-cloud-modules-iac/
        
    - name: Copy Azure modules
      if: ${{ github.event.inputs.module_type == 'azure' || github.event.inputs.module_type == 'all' }}
      run: |
        if [ -d "terraform-cloud-modules-iac/azure" ] && [ "$(ls -A terraform-cloud-modules-iac/azure)" ]; then
          cp -r terraform-cloud-modules-iac/azure/* ${{ github.event.inputs.destination_path }}/
          echo "Azure modules copied to ${{ github.event.inputs.destination_path }}"
        else
          echo "Azure modules directory is empty or does not exist"
        fi
        
    - name: Copy AWS modules
      if: ${{ github.event.inputs.module_type == 'aws' || github.event.inputs.module_type == 'all' }}
      run: |
        if [ -d "terraform-cloud-modules-iac/aws" ] && [ "$(ls -A terraform-cloud-modules-iac/aws)" ]; then
          cp -r terraform-cloud-modules-iac/aws/* ${{ github.event.inputs.destination_path }}/
          echo "AWS modules copied to ${{ github.event.inputs.destination_path }}"
        else
          echo "AWS modules directory is empty or does not exist"
        fi
        
    - name: Copy GCP modules
      if: ${{ github.event.inputs.module_type == 'gcp' || github.event.inputs.module_type == 'all' }}
      run: |
        if [ -d "terraform-cloud-modules-iac/gcp" ] && [ "$(ls -A terraform-cloud-modules-iac/gcp)" ]; then
          cp -r terraform-cloud-modules-iac/gcp/* ${{ github.event.inputs.destination_path }}/
          echo "GCP modules copied to ${{ github.event.inputs.destination_path }}"
        else
          echo "GCP modules directory is empty or does not exist"
        fi
        
    - name: List copied modules
      run: |
        echo "Contents of destination directory:"
        ls -la ${{ github.event.inputs.destination_path }} || echo "Destination directory is empty or does not exist"
        



