name: 'Terraform Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - qa
          - sbx
      module_branch:
        description: 'Branch to fetch from terraform-cloud-modules-iac'
        required: false
        default: 'develop'
        type: string

permissions:
  contents: read
  pull-requests: write
  packages: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      TF_WORKING_DIR: ./azure/scripts
      CREDS: >-
        ${{
          (github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'qa') && secrets.AZURE_PROD_CICD ||
          github.event.inputs.environment == 'sbx' && secrets.AZURE_SBX_CICD ||
          secrets.AZURE_NONPROD_CICD
        }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Mask sensitive values
        run: |
          echo "::add-mask::${{ fromJson(env.CREDS).clientId }}"
          echo "::add-mask::${{ fromJson(env.CREDS).clientSecret }}"
          echo "::add-mask::${{ fromJson(env.CREDS).tenantId }}"
          echo "::add-mask::${{ fromJson(env.CREDS).subscriptionId }}"

      - name: Export ARM credentials to environment
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(env.CREDS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(env.CREDS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(env.CREDS).tenantId }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(env.CREDS).subscriptionId }}" >> $GITHUB_ENV

      - name: Checkout terraform-cloud-modules-iac
        uses: actions/checkout@v4
        with:
          repository: joselrnz/terraform-cloud-modules-iac
          ref: ${{ github.event.inputs.module_branch }}
          token: ${{ secrets.API_TOKEN_TF }}
          path: terraform-cloud-modules-iac

      - name: Copy modules to correct location
        run: |
          mkdir -p modules
          if [ -d "terraform-cloud-modules-iac/azure" ]; then
            cp -r terraform-cloud-modules-iac/azure/* modules/
            echo "Azure modules copied to modules/"
          else
            echo "Azure modules directory not found in terraform-cloud-modules-iac"
            exit 1
          fi

      # ✅ TFLint
      - name: Install and Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint --recursive

      # ✅ TFSEC
      - name: tfsec - Static Security Analysis (includes modules)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: .

      # ✅ Checkov
      - name: Checkov - Compliance and Security Check
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ env.CREDS }}
          enable-AzPSSession: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=data-dp203" \
            -backend-config="storage_account_name=terraformstateclouddev" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Confirm tfvars file exists and inspect structure
        run: |
          echo "Looking for tfvars file: ../../azure/env/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars"
          find ../.. -type f
          test -f ../../azure/env/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars || {
            echo "ERROR: tfvars file not found!" >&2
            exit 1
          }
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var-file="../../azure/env/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars" \
            -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: |
          terraform apply \
            -var-file="../../azure/env/${{ github.event.inputs.environment }}/${{ github.event.inputs.environment }}.tfvars" \
            -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
